name: Caller for Multilingual WF

on:
  workflow_dispatch:

jobs:
  caller-workflow:
    name: Call Azure Functions WF
    uses: missAnkita/Reusable-Workflows/.github/workflows/multilingual-wf.yml@main
    with:
      runs-on: ubuntu-latest
      run-tests: false
      project-folder: .
