name: Caller WF AZ functions code

on:
  workflow_dispatch:

jobs:
  all:
      name: Call Azure Functions WF
      uses: missAnkita/Reusable-Workflows/.github/workflows/multilingual-wf.yml@main
      with:
        runs-on: ubuntu-latest
        run-tests: false
        project-folder: .
      secrets: inherit
