name: Caller for Multilingual WF

on:
  workflow_dispatch:
    inputs:
      working-directory:
        description: 'working directory for App code'
        required: true
        type: string
        default: .
      framework:
        description: 'The type of framework or service'
        required: true
        default: azure-functions
        type: string


jobs:
  caller-workflow:
    uses: missAnkita/Reusable-Workflows/.github/workflows/multilingual-wf.yml@feature/test-multilingual
    with:
      working-directory: .
      framework: ${{ github.event.inputs.framework }}
